# Generated by Django 6.0 on 2025-12-12 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectRed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hamperrequest',
            old_name='notes',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='hamperrequest',
            name='status',
        ),
    ]
